### ISSUE TITLE
使用SIFT方式时，报下面错误，这个如何解决？多谢

### ISSUE THREAD

**Issue by pxrgod** [hakaboom/image_registration#8]
AttributeError: module 'cv2' has no attribute 'USAC_MAGSAC'

**Comment by hakaboom** [comment]
检查下你的opencv版本，应该是4.5.0以上才有的功能

**Comment by pxrgod** [comment]
> 检查下你的opencv版本，应该是4.5.0以上才有的功能

是的，我opencv版本问题。多谢
